/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.malimar.views;

import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author Malimar
 */
public class FrmTitle extends javax.swing.JDialog {

    /**
     * Creates new form FrmDivision
     */
    public FrmTitle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbTitle.setUI(new BasicComboBoxUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        menuExit = new com.xzq.osc.JocHyperlink();
        lbllblTitleInfor = new javax.swing.JLabel();
        jocTabbedPane1 = new com.xzq.osc.JocTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        txtTitleID = new javax.swing.JTextField();
        lblTitleID = new javax.swing.JLabel();
        txtTitle_L1 = new javax.swing.JTextField();
        lblTitle_L1 = new javax.swing.JLabel();
        btnSave = new com.xzq.osc.JocHyperlink();
        panelSave = new com.xzq.osc.JocHyperlink();
        panelHover = new com.xzq.osc.JocHyperlink();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitle_L2 = new javax.swing.JLabel();
        txtTitle_L2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblJonDuties = new javax.swing.JLabel();
        cmbTitle = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblJobDutiesID = new javax.swing.JLabel();
        txtJobDutiesID = new javax.swing.JTextField();
        lblJobDuties_L1 = new javax.swing.JLabel();
        txtJobDuties_L1 = new javax.swing.JTextField();
        lblJobDuties_L2 = new javax.swing.JLabel();
        txtJobDuties_L2 = new javax.swing.JTextField();
        btnSave1 = new com.xzq.osc.JocHyperlink();
        panelSave1 = new com.xzq.osc.JocHyperlink();
        panelHover1 = new com.xzq.osc.JocHyperlink();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(81, 87, 99), 2, true));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(81, 87, 99));

        menuExit.setActiveColor(new java.awt.Color(255, 50, 50));
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malimar/icons/Delete_30px.png"))); // NOI18N
        menuExit.setUnvisitColor(new java.awt.Color(255, 255, 255));
        menuExit.setFont(new java.awt.Font("Saysettha OT", 1, 12)); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });

        lbllblTitleInfor.setFont(new java.awt.Font("Saysettha OT", 1, 12)); // NOI18N
        lbllblTitleInfor.setForeground(new java.awt.Color(255, 255, 255));
        lbllblTitleInfor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllblTitleInfor.setText("Title Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbllblTitleInfor, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbllblTitleInfor)
                    .addComponent(menuExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 656, 30);

        jocTabbedPane1.setShowCloseButton(false);
        jocTabbedPane1.setShowListButton(false);
        jocTabbedPane1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        txtTitleID.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtTitleID.setText("New");
        txtTitleID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel5.add(txtTitleID);
        txtTitleID.setBounds(170, 20, 100, 25);

        lblTitleID.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblTitleID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitleID.setText("ID");
        jPanel5.add(lblTitleID);
        lblTitleID.setBounds(30, 20, 120, 25);

        txtTitle_L1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtTitle_L1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel5.add(txtTitle_L1);
        txtTitle_L1.setBounds(170, 60, 300, 25);

        lblTitle_L1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblTitle_L1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle_L1.setText("Title(Lao)");
        jPanel5.add(lblTitle_L1);
        lblTitle_L1.setBounds(30, 60, 120, 25);

        btnSave.setText("Save");
        btnSave.setUnvisitColor(new java.awt.Color(255, 255, 255));
        btnSave.setVisitedColor(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel5.add(btnSave);
        btnSave.setBounds(386, 183, 83, 26);

        panelSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malimar/images/Button.png"))); // NOI18N
        panelSave.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel5.add(panelSave);
        panelSave.setBounds(380, 180, 96, 32);

        panelHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malimar/images/ButtonHover.png"))); // NOI18N
        panelHover.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel5.add(panelHover);
        panelHover.setBounds(380, 180, 96, 32);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "lblID", "lblTitle_L1", "lblTitle_L2", "lblJobDuties"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(java.awt.Color.red);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setMinWidth(207);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(207);
            jTable1.getColumnModel().getColumn(2).setMinWidth(207);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(207);
            jTable1.getColumnModel().getColumn(3).setMinWidth(210);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(210);
        }

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel4);
        jPanel4.setBounds(10, 220, 632, 370);

        lblTitle_L2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblTitle_L2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle_L2.setText("Title(EN)");
        jPanel5.add(lblTitle_L2);
        lblTitle_L2.setBounds(30, 100, 120, 25);

        txtTitle_L2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtTitle_L2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel5.add(txtTitle_L2);
        txtTitle_L2.setBounds(170, 100, 300, 25);
        jPanel5.add(jSeparator6);
        jSeparator6.setBounds(170, 163, 300, 10);

        lblJonDuties.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblJonDuties.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJonDuties.setText("Job duties");
        jPanel5.add(lblJonDuties);
        lblJonDuties.setBounds(30, 140, 120, 25);

        cmbTitle.setEditable(true);
        cmbTitle.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        cmbTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 1));
        jPanel5.add(cmbTitle);
        cmbTitle.setBounds(170, 140, 300, 25);

        jocTabbedPane1.addTab("Title", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        lblJobDutiesID.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblJobDutiesID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJobDutiesID.setText("ID");
        jPanel6.add(lblJobDutiesID);
        lblJobDutiesID.setBounds(30, 20, 120, 25);

        txtJobDutiesID.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtJobDutiesID.setText("New");
        txtJobDutiesID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel6.add(txtJobDutiesID);
        txtJobDutiesID.setBounds(170, 20, 100, 25);

        lblJobDuties_L1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblJobDuties_L1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJobDuties_L1.setText("Job Duties(Lao)");
        jPanel6.add(lblJobDuties_L1);
        lblJobDuties_L1.setBounds(30, 60, 120, 25);

        txtJobDuties_L1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtJobDuties_L1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel6.add(txtJobDuties_L1);
        txtJobDuties_L1.setBounds(170, 60, 300, 25);

        lblJobDuties_L2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        lblJobDuties_L2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJobDuties_L2.setText("Job Duties(EN)");
        jPanel6.add(lblJobDuties_L2);
        lblJobDuties_L2.setBounds(30, 100, 120, 25);

        txtJobDuties_L2.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtJobDuties_L2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        jPanel6.add(txtJobDuties_L2);
        txtJobDuties_L2.setBounds(170, 100, 300, 25);

        btnSave1.setText("Save");
        btnSave1.setUnvisitColor(new java.awt.Color(255, 255, 255));
        btnSave1.setVisitedColor(new java.awt.Color(255, 255, 255));
        btnSave1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel6.add(btnSave1);
        btnSave1.setBounds(386, 153, 83, 26);

        panelSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malimar/images/Button.png"))); // NOI18N
        panelSave1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel6.add(panelSave1);
        panelSave1.setBounds(380, 150, 96, 32);

        panelHover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/malimar/images/ButtonHover.png"))); // NOI18N
        panelHover1.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jPanel6.add(panelHover1);
        panelHover1.setBounds(380, 150, 96, 32);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        table.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "lblJobDutiesID", "lblJobDuties_L1", "lblJobDuties_L2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setGridColor(new java.awt.Color(204, 204, 204));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(java.awt.Color.red);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(100);
            table.getColumnModel().getColumn(0).setMaxWidth(100);
            table.getColumnModel().getColumn(1).setMinWidth(265);
            table.getColumnModel().getColumn(1).setMaxWidth(265);
            table.getColumnModel().getColumn(2).setMinWidth(260);
            table.getColumnModel().getColumn(2).setMaxWidth(260);
        }

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(10, 200, 630, 390);

        jocTabbedPane1.addTab("Job Duties", jPanel6);

        jPanel2.add(jocTabbedPane1);
        jocTabbedPane1.setBounds(0, 30, 656, 640);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
         this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmTitle dialog = new FrmTitle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.xzq.osc.JocHyperlink btnSave;
    private com.xzq.osc.JocHyperlink btnSave1;
    private javax.swing.JComboBox<String> cmbTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private com.xzq.osc.JocTabbedPane jocTabbedPane1;
    private javax.swing.JLabel lblJobDutiesID;
    private javax.swing.JLabel lblJobDuties_L1;
    private javax.swing.JLabel lblJobDuties_L2;
    private javax.swing.JLabel lblJonDuties;
    private javax.swing.JLabel lblTitleID;
    private javax.swing.JLabel lblTitle_L1;
    private javax.swing.JLabel lblTitle_L2;
    private javax.swing.JLabel lbllblTitleInfor;
    private com.xzq.osc.JocHyperlink menuExit;
    private com.xzq.osc.JocHyperlink panelHover;
    private com.xzq.osc.JocHyperlink panelHover1;
    private com.xzq.osc.JocHyperlink panelSave;
    private com.xzq.osc.JocHyperlink panelSave1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtJobDutiesID;
    private javax.swing.JTextField txtJobDuties_L1;
    private javax.swing.JTextField txtJobDuties_L2;
    private javax.swing.JTextField txtTitleID;
    private javax.swing.JTextField txtTitle_L1;
    private javax.swing.JTextField txtTitle_L2;
    // End of variables declaration//GEN-END:variables
}
